import { chromium } from "playwright";
const B = process.env.BASE_URL ?? "https://ztor-video.mluthfi840.workers.dev", FILM = process.env.FILM ?? "439662d9-e97b-44f5-9ae1-7bd346553e4b";
const APP = "2ed55f309dc460453ab0b9157b6496c2", SECRET = process.env.SFU_SECRET;
const j = async (m, p, body, h = {}) => { const r = await fetch(B + p, { method: m, headers: { "content-type": "application/json", ...h }, body: body ? JSON.stringify(body) : undefined }); return { s: r.status, b: await r.json().catch(() => null) }; };
const sleep = (ms) => new Promise(r => setTimeout(r, ms));
const out = (k, v) => console.log(k.padEnd(34), typeof v === "string" ? v : JSON.stringify(v));
const c = await j("POST", "/party", { hostId: "host-1", filmId: FILM, title: "simulcast test" }); const id = c.b.partyId; out("party", id);
const browser = await chromium.launch({ channel: "chrome", headless: true, args: ["--use-fake-device-for-media-stream", "--use-fake-ui-for-media-stream", "--autoplay-policy=no-user-gesture-required"] });
const ctx = await browser.newContext({ permissions: ["camera", "microphone"] });
const logOf = (page) => page.evaluate(() => document.getElementById("log").textContent);
const waitLog = async (page, re, ms = 20000) => { const t0 = Date.now(); while (Date.now() - t0 < ms) { if (re.test(await logOf(page))) return true; await sleep(300); } return false; };
const host = await ctx.newPage(); await host.goto(`${B}/watch?party=${id}&user=host-1`); await waitLog(host, /room connected/);
await host.click("#bCam"); out("host published", await waitLog(host, /published cam, mic/));
out("host simulcast in SDP", (await logOf(host)).match(/simulcast [^)]*/)?.[0]);
const hostLayers = () => host.evaluate(async () => { const e = hostGroups.get("cam"); const st = await e.pc.getStats(); const o = []; st.forEach(s => { if (s.type === "outbound-rtp" && s.kind === "video") o.push({ rid: s.rid, w: s.frameWidth, h: s.frameHeight, kbps: s.targetBitrate ? Math.round(s.targetBitrate / 1000) : null, bytes: s.bytesSent, active: s.active }); }); return o; });
const fan = await ctx.newPage(); await fan.goto(`${B}/watch?party=${id}&user=fan-1`); await waitLog(fan, /room connected/); await fan.click("#bGate");
out("fan receives", await waitLog(fan, /receiving cam/)); await sleep(8000);
out("host outbound layers", await hostLayers());
const fanVideo = () => fan.evaluate(async () => { const c = [...viewerConns.values()][0]; const st = await c.pc.getStats(); let r = null; st.forEach(s => { if (s.type === "inbound-rtp" && s.kind === "video") r = { w: s.frameWidth, h: s.frameHeight, fps: s.framesPerSecond, bytes: s.bytesReceived, lost: s.packetsLost }; }); return { ...r, layer: [...layerState.values()][0]?.rid, tile: `${document.getElementById("cam").videoWidth}x${document.getElementById("cam").videoHeight}` }; });
out("fan receiving (layer a)", await fanVideo());
await fan.evaluate(() => forceLayer("c")); out("fan asked for c", await waitLog(fan, /layer -> c/, 10000)); await sleep(7000);
out("fan receiving (layer c)", await fanVideo());
await fan.evaluate(() => forceLayer("b")); await waitLog(fan, /layer -> b/, 10000); await sleep(7000);
out("fan receiving (layer b)", await fanVideo());
await fan.evaluate(() => forceLayer("a")); await waitLog(fan, /layer -> a/, 10000); await sleep(7000);
out("fan receiving (layer a again, 7 s)", await fanVideo()); await sleep(15000); out("fan receiving (layer a, +22 s)", await fanVideo()); await sleep(15000); out("fan receiving (layer a, +37 s)", await fanVideo());
// bad request paths
const tok = await fan.evaluate(() => me.token); const st = await fan.evaluate(() => { const s = [...layerState.values()][0]; return { sessionId: s.conn.sessionId, mid: s.mid, hostSessionId: s.hs, trackName: s.trackName }; });
out("layer z refused (400)", (await j("PUT", `/party/${id}/rtc/layer`, { ...st, rid: "z" }, { authorization: "Bearer " + tok })).s);
out("layer on unknown track (404)", (await j("PUT", `/party/${id}/rtc/layer`, { ...st, trackName: "nope-9", rid: "b" }, { authorization: "Bearer " + tok })).s);
console.log("---- fan log tail ----\n" + (await logOf(fan)).split("\n").slice(-8).join("\n"));
await j("POST", `/party/${id}/end`, {}, { authorization: "Bearer " + (await host.evaluate(() => me.token)) });
await browser.close();
